services:
  - type: web
    name: expense-ai-bot
    env: python
    branch: main
    startCommand: python main.py
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
    plan: free
